# Form implementation generated from reading ui file 'add_info_teacherUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(460, 310)
        dialog.setStyleSheet("QDialog {\n"
"    background: #F5FaFE;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #1E95FE;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    padding: 0px 8px;\n"
"}"
"\n"
                             "QTextEdit {\n"
                             "    border: 1px solid black;\n"
                             "    border-radius: 10px;\n"
                             "    padding: 0px 8px;\n"
                             "    font-size: 12px;\n"
                             "}"
                             )
        self.addBtn = QtWidgets.QPushButton(parent=dialog)
        self.addBtn.setGeometry(QtCore.QRect(290, 250, 113, 32))
        self.addBtn.setObjectName("addBtn")
        self.cancelBtn = QtWidgets.QPushButton(parent=dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(70, 250, 113, 32))
        self.cancelBtn.setObjectName("cancelBtn")
        self.addTeacherComboBox = QtWidgets.QComboBox(parent=dialog)
        self.addTeacherComboBox.setGeometry(QtCore.QRect(290, 30, 121, 26))
        self.addTeacherComboBox.setObjectName("addTeacherComboBox")
        self.addTeacherLable = QtWidgets.QLabel(parent=dialog)
        self.addTeacherLable.setGeometry(QtCore.QRect(70, 30, 191, 21))
        self.addTeacherLable.setObjectName("addTeacherLable")
        self.ExpirienceLable = QtWidgets.QLabel(parent=dialog)
        self.ExpirienceLable.setGeometry(QtCore.QRect(70, 80, 60, 21))
        self.ExpirienceLable.setObjectName("ExpirienceLable")
        self.ExpirienceEdit = QtWidgets.QLineEdit(parent=dialog)
        self.ExpirienceEdit.setGeometry(QtCore.QRect(300, 80, 41, 21))
        self.ExpirienceEdit.setObjectName("ExpirienceEdit")
        self.shortInfoLable = QtWidgets.QLabel(parent=dialog)
        self.shortInfoLable.setGeometry(QtCore.QRect(70, 120, 171, 21))
        self.shortInfoLable.setObjectName("shortInfoLable")
        self.shorInfoEdit = QtWidgets.QTextEdit(parent=dialog)
        self.shorInfoEdit.setGeometry(QtCore.QRect(70, 150, 331, 91))
        self.shorInfoEdit.setObjectName("shorInfoEdit")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Добавить на страницу"))
        self.addBtn.setText(_translate("dialog", "Добавить"))
        self.cancelBtn.setText(_translate("dialog", "Отменить"))
        self.addTeacherLable.setText(_translate("dialog", "Выбрать преподавателя"))
        self.ExpirienceLable.setText(_translate("dialog", "Стаж"))
        self.shortInfoLable.setText(_translate("dialog", "Краткая информация"))
