# Form implementation generated from reading ui file 'addInfoDialogUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(659, 380)
        Dialog.setStyleSheet("QDialog {\n"
"    background: #F5FaFE;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #1E95FE;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    padding: 0px 8px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    padding: 0px 8px;\n"
"    font-size: 12px;\n"
"}")
        self.titleLable = QtWidgets.QLabel(parent=Dialog)
        self.titleLable.setGeometry(QtCore.QRect(30, 30, 111, 31))
        self.titleLable.setObjectName("titleLable")
        self.infoLable = QtWidgets.QLabel(parent=Dialog)
        self.infoLable.setGeometry(QtCore.QRect(30, 116, 111, 20))
        self.infoLable.setObjectName("infoLable")
        self.titleInput = QtWidgets.QLineEdit(parent=Dialog)
        self.titleInput.setGeometry(QtCore.QRect(30, 70, 601, 31))
        self.titleInput.setText("")
        self.titleInput.setObjectName("titleInput")
        self.infoEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.infoEdit.setGeometry(QtCore.QRect(30, 150, 601, 151))
        self.infoEdit.setObjectName("infoEdit")
        self.cancelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(370, 320, 113, 32))
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelBtn.setObjectName("cancelBtn")
        self.confirmBtn = QtWidgets.QPushButton(parent=Dialog)
        self.confirmBtn.setGeometry(QtCore.QRect(510, 320, 113, 32))
        self.confirmBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.confirmBtn.setObjectName("confirmBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить информацию"))
        self.titleLable.setText(_translate("Dialog", "Заголовок"))
        self.infoLable.setText(_translate("Dialog", "Содержание"))
        self.infoEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:12px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.cancelBtn.setText(_translate("Dialog", "Отменить"))
        self.confirmBtn.setText(_translate("Dialog", "Добавить"))
