# Form implementation generated from reading ui file 'addScheduleUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 237)
        Dialog.setStyleSheet("QDialog {\n"
"    background: #F5FaFE;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #1E95FE;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    padding: 0px 8px;\n"
"}")
        self.name_label = QtWidgets.QLabel(parent=Dialog)
        self.name_label.setGeometry(QtCore.QRect(20, 30, 151, 21))
        self.name_label.setObjectName("name_label")
        self.name_edit = QtWidgets.QLineEdit(parent=Dialog)
        self.name_edit.setGeometry(QtCore.QRect(180, 30, 171, 21))
        self.name_edit.setObjectName("name_edit")
        self.day_label = QtWidgets.QLabel(parent=Dialog)
        self.day_label.setGeometry(QtCore.QRect(20, 90, 101, 21))
        self.day_label.setObjectName("day_label")
        self.day_combo = QtWidgets.QComboBox(parent=Dialog)
        self.day_combo.setGeometry(QtCore.QRect(180, 90, 161, 31))
        self.day_combo.setObjectName("day_combo")
        self.time_label = QtWidgets.QLabel(parent=Dialog)
        self.time_label.setGeometry(QtCore.QRect(20, 140, 71, 21))
        self.time_label.setObjectName("time_label")
        self.time_edit = QtWidgets.QTimeEdit(parent=Dialog)
        self.time_edit.setGeometry(QtCore.QRect(180, 140, 161, 24))
        self.time_edit.setObjectName("time_edit")
        self.add_button = QtWidgets.QPushButton(parent=Dialog)
        self.add_button.setGeometry(QtCore.QRect(140, 190, 113, 32))
        self.add_button.setObjectName("add_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить занятие"))
        self.name_label.setText(_translate("Dialog", "Название занятия"))
        self.day_label.setText(_translate("Dialog", "День недели"))
        self.time_label.setText(_translate("Dialog", "Время"))
        self.add_button.setText(_translate("Dialog", "Добавить"))
