# Form implementation generated from reading ui file 'changePassUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUiChange(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 210)
        Dialog.setStyleSheet("QDialog {\n"
"    background: #1E95FE;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #1F95EF;\n"
"    background: #F5FAFE;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 0px 8px;\n"
"}\n"
"\n"
"")
        self.reNewPassInput = QtWidgets.QLineEdit(parent=Dialog)
        self.reNewPassInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.reNewPassInput.setGeometry(QtCore.QRect(180, 90, 171, 21))
        self.reNewPassInput.setStyleSheet("")
        self.reNewPassInput.setPlaceholderText("")
        self.reNewPassInput.setObjectName("reNewPassInput")
        self.reNewPassLable = QtWidgets.QLabel(parent=Dialog)
        self.reNewPassLable.setGeometry(QtCore.QRect(40, 90, 111, 21))
        self.reNewPassLable.setStyleSheet("background: transparent;\n"
"font-size: 16px;")
        self.reNewPassLable.setObjectName("reNewPassLable")
        self.cancelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(40, 150, 131, 32))
        self.cancelBtn.setStyleSheet("")
        self.cancelBtn.setObjectName("cancelBtn")
        self.newPassLable = QtWidgets.QLabel(parent=Dialog)
        self.newPassLable.setGeometry(QtCore.QRect(40, 30, 111, 21))
        self.newPassLable.setStyleSheet("background: transparent;\n"
"font-size: 16px;")
        self.newPassLable.setObjectName("newPassLable")
        self.savePassBtn = QtWidgets.QPushButton(parent=Dialog)
        self.savePassBtn.setGeometry(QtCore.QRect(230, 150, 131, 32))
        self.savePassBtn.setStyleSheet("")
        self.savePassBtn.setObjectName("savePassBtn")
        self.newPassInput = QtWidgets.QLineEdit(parent=Dialog)
        self.newPassInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.newPassInput.setGeometry(QtCore.QRect(180, 30, 171, 21))
        self.newPassInput.setStyleSheet("")
        self.newPassInput.setText("")
        self.newPassInput.setPlaceholderText("")
        self.newPassInput.setObjectName("newPassInput")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Изменить пароль"))
        self.reNewPassLable.setText(_translate("Dialog", "Повторите"))
        self.cancelBtn.setText(_translate("Dialog", "Отменить"))
        self.newPassLable.setText(_translate("Dialog", "Новый пароль"))
        self.savePassBtn.setText(_translate("Dialog", "Сохранить"))
