# Form implementation generated from reading ui file 'deleteInfoDialogUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogDelete(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(323, 189)
        Dialog.setStyleSheet("QDialog {\n"
"    background: #F5FaFE;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #1E95FE;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}")
        self.deleteTitle = QtWidgets.QLabel(parent=Dialog)
        self.deleteTitle.setGeometry(QtCore.QRect(20, 20, 281, 21))
        self.deleteTitle.setObjectName("deleteTitle")
        self.titleComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.titleComboBox.setGeometry(QtCore.QRect(20, 70, 161, 26))
        self.titleComboBox.setObjectName("titleComboBox")
        self.cancelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(20, 120, 113, 32))
        self.cancelBtn.setObjectName("cancelBtn")
        self.deleteBtn = QtWidgets.QPushButton(parent=Dialog)
        self.deleteBtn.setGeometry(QtCore.QRect(170, 120, 113, 32))
        self.deleteBtn.setObjectName("deleteBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Удалить новость"))
        self.deleteTitle.setText(_translate("Dialog", "Выберите заголовок для удаления"))
        self.cancelBtn.setText(_translate("Dialog", "Отмена"))
        self.deleteBtn.setText(_translate("Dialog", "Удалить"))
