# Form implementation generated from reading ui file 'delete_info_teacherUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(437, 174)
        Dialog.setStyleSheet("QDialog {\n"
"    background: #F5FaFE;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #1E95FE;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    padding: 0px 8px;\n"
"}")
        self.selectTeacherLsbel = QtWidgets.QLabel(parent=Dialog)
        self.selectTeacherLsbel.setGeometry(QtCore.QRect(30, 50, 201, 21))
        self.selectTeacherLsbel.setObjectName("selectTeacherLsbel")
        self.selectTeacherComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.selectTeacherComboBox.setGeometry(QtCore.QRect(240, 50, 171, 26))
        self.selectTeacherComboBox.setObjectName("selectTeacherComboBox")
        self.cancelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(60, 120, 113, 32))
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelBtn.setObjectName("cancelBtn")
        self.deleteBtn = QtWidgets.QPushButton(parent=Dialog)
        self.deleteBtn.setGeometry(QtCore.QRect(270, 120, 113, 32))
        self.deleteBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.deleteBtn.setObjectName("deleteBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Удалить"))
        self.selectTeacherLsbel.setText(_translate("Dialog", "Выбрать преподавателя"))
        self.cancelBtn.setText(_translate("Dialog", "Отмена"))
        self.deleteBtn.setText(_translate("Dialog", "Удалить"))
