# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(367, 591)
        Form.setStyleSheet("QWidget {\n"
"    background: #1E95FE;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #1F95EF;\n"
"    background: #F5FAFE;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 0px 8px; color: white;\n"
"}")
        self.exitBtn = QtWidgets.QPushButton(parent=Form)
        self.exitBtn.setGeometry(QtCore.QRect(130, 424, 113, 32))
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.exitBtn.setStyleSheet("")
        self.exitBtn.setObjectName("exitBtn")
        self.passLable = QtWidgets.QLabel(parent=Form)
        self.passLable.setGeometry(QtCore.QRect(150, 274, 71, 21))
        self.passLable.setStyleSheet("background: transparent;\n"
"font-size: 16px;")
        self.passLable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.passLable.setObjectName("passLable")
        self.passInput = QtWidgets.QLineEdit(parent=Form)
        self.passInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passInput.setGeometry(QtCore.QRect(112, 304, 151, 21))
        self.passInput.setStyleSheet("")
        self.passInput.setObjectName("passInput")
        self.loginLable = QtWidgets.QLabel(parent=Form)
        self.loginLable.setGeometry(QtCore.QRect(150, 204, 71, 21))
        self.loginLable.setStyleSheet("background: transparent;\n"
"font-size: 16px;")
        self.loginLable.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.loginLable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loginLable.setObjectName("loginLable")
        self.createAccBtn = QtWidgets.QPushButton(parent=Form)
        self.createAccBtn.setGeometry(QtCore.QRect(230, 494, 113, 32))
        self.createAccBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.createAccBtn.setStyleSheet("")
        self.createAccBtn.setObjectName("createAccBtn")
        self.picture = QtWidgets.QLabel(parent=Form)
        self.picture.setGeometry(QtCore.QRect(150, 34, 131, 111))
        self.picture.setStyleSheet("background: transparent;\n"
"font-size: 30px;\n"
"border: none;")
        self.picture.setWordWrap(True)
        self.picture.setObjectName("picture")
        self.loginInput = QtWidgets.QLineEdit(parent=Form)
        self.loginInput.setGeometry(QtCore.QRect(112, 234, 151, 21))
        self.loginInput.setStyleSheet("")
        self.loginInput.setObjectName("loginInput")
        self.logBtn = QtWidgets.QPushButton(parent=Form)
        self.logBtn.setGeometry(QtCore.QRect(130, 374, 113, 32))
        self.logBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.logBtn.setStyleSheet("")
        self.logBtn.setObjectName("logBtn")
        self.createAccLable = QtWidgets.QLabel(parent=Form)
        self.createAccLable.setGeometry(QtCore.QRect(20, 500, 171, 20))
        self.createAccLable.setStyleSheet("background: transparent;\n"
"font-size: 16px;")
        self.createAccLable.setObjectName("createAccLable")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.exitBtn.setText(_translate("Form", "Выйти"))
        self.passLable.setText(_translate("Form", "Пароль"))
        self.loginLable.setText(_translate("Form", "Логин"))
        self.createAccBtn.setText(_translate("Form", "Создать"))
        self.picture.setText(_translate("Form", "Ехай"))
        self.logBtn.setText(_translate("Form", "Войти"))
        self.createAccLable.setText(_translate("Form", "Еще нет аккаунта?"))
