# Form implementation generated from reading ui file 'notificationUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogNot(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(546, 300)
        Dialog.setStyleSheet("QDialog {background: #F5FaFE;}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #1E95FE;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}")
        self.notoficationLable = QtWidgets.QLabel(parent=Dialog)
        self.notoficationLable.setGeometry(QtCore.QRect(369, 20, 141, 31))
        self.notoficationLable.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.notoficationLable.setObjectName("notoficationLable")
        self.closeBtn = QtWidgets.QPushButton(parent=Dialog)
        self.closeBtn.setGeometry(QtCore.QRect(30, 20, 113, 32))
        self.closeBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.closeBtn.setObjectName("closeBtn")
        self.notificationEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.notificationEdit.setGeometry(QtCore.QRect(30, 70, 491, 171))
        self.notificationEdit.setReadOnly(True)
        self.notificationEdit.setObjectName("notificationEdit")
        self.clearBtn = QtWidgets.QPushButton(parent=Dialog)
        self.clearBtn.setGeometry(QtCore.QRect(400, 250, 113, 32))
        self.clearBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.clearBtn.setObjectName("clearBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Уведомления"))
        self.notoficationLable.setText(_translate("Dialog", "Уведомления"))
        self.closeBtn.setText(_translate("Dialog", "Закрыть"))
        self.clearBtn.setText(_translate("Dialog", "Очистить"))
