# Form implementation generated from reading ui file 'registration_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 596)
        Form.setStyleSheet("QWidget {\n"
"    background: #1E95FE;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #1F95EF;\n"
"    background: #F5FAFE;\n"
"    font-weight: bold;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid white;\n"
"    border-radius: 10px;\n"
"    padding: 0px 8px;\n"
"}")
        self.createAccLable = QtWidgets.QLabel(parent=Form)
        self.createAccLable.setGeometry(QtCore.QRect(30, 486, 171, 20))
        self.createAccLable.setStyleSheet("background: transparent;\n"
"font-size: 16px;")
        self.createAccLable.setObjectName("createAccLable")
        self.passInput = QtWidgets.QLineEdit(parent=Form)
        self.passInput.setGeometry(QtCore.QRect(122, 250, 151, 21))
        self.passInput.setStyleSheet("")
        self.passInput.setObjectName("passInput")
        self.passLable = QtWidgets.QLabel(parent=Form)
        self.passLable.setGeometry(QtCore.QRect(160, 220, 71, 21))
        self.passLable.setStyleSheet("background: transparent;\n"
"font-size: 16px;")
        self.passLable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.passLable.setObjectName("passLable")
        self.loginLable = QtWidgets.QLabel(parent=Form)
        self.loginLable.setGeometry(QtCore.QRect(160, 160, 71, 21))
        self.loginLable.setStyleSheet("background: transparent;\n"
"font-size: 16px;")
        self.loginLable.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.loginLable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.loginLable.setObjectName("loginLable")
        self.picture = QtWidgets.QLabel(parent=Form)
        self.picture.setGeometry(QtCore.QRect(130, 20, 131, 121))
        self.picture.setStyleSheet("background: transparent;\n"
"font-size: 30px;\n"
"border: none;")
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap("photo_2024-06-15_14-05-17.jpg"))
        self.picture.setScaledContents(True)
        self.picture.setWordWrap(True)
        self.picture.setObjectName("picture")
        self.regBtn = QtWidgets.QPushButton(parent=Form)
        self.regBtn.setGeometry(QtCore.QRect(120, 360, 151, 32))
        self.regBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.regBtn.setStyleSheet("")
        self.regBtn.setObjectName("regBtn")
        self.loginInput = QtWidgets.QLineEdit(parent=Form)
        self.loginInput.setGeometry(QtCore.QRect(122, 190, 151, 21))
        self.loginInput.setStyleSheet("")
        self.loginInput.setObjectName("loginInput")
        self.inputBtn = QtWidgets.QPushButton(parent=Form)
        self.inputBtn.setGeometry(QtCore.QRect(240, 480, 121, 32))
        self.inputBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.inputBtn.setStyleSheet("")
        self.inputBtn.setObjectName("inputBtn")
        self.exitBtn = QtWidgets.QPushButton(parent=Form)
        self.exitBtn.setGeometry(QtCore.QRect(140, 410, 113, 32))
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.exitBtn.setStyleSheet("")
        self.exitBtn.setObjectName("exitBtn")
        self.rePassLable = QtWidgets.QLabel(parent=Form)
        self.rePassLable.setGeometry(QtCore.QRect(120, 280, 161, 21))
        self.rePassLable.setStyleSheet("background: transparent;\n"
"font-size: 16px;")
        self.rePassLable.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rePassLable.setObjectName("rePassLable")
        self.rePassInput = QtWidgets.QLineEdit(parent=Form)
        self.rePassInput.setGeometry(QtCore.QRect(122, 310, 151, 21))
        self.rePassInput.setStyleSheet("")
        self.rePassInput.setObjectName("rePassInput")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(150, 30, 141, 91))
        self.label.setStyleSheet("font-size: 40px;")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Регистрация"))
        self.createAccLable.setText(_translate("Form", "Уже есть аккаунт?"))
        self.passLable.setText(_translate("Form", "Пароль"))
        self.loginLable.setText(_translate("Form", "Логин"))
        self.regBtn.setText(_translate("Form", "Зарегестрироваться"))
        self.inputBtn.setText(_translate("Form", "Войти в аккаунт"))
        self.exitBtn.setText(_translate("Form", "Выйти"))
        self.rePassLable.setText(_translate("Form", "Повторите пароль"))
        self.label.setText(_translate("Form", "Ехай"))
