# Form implementation generated from reading ui file 'show_recordsUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(422, 239)
        Dialog.setStyleSheet("QDialog {\n"
"    background: #F5FaFE;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #1E95FE;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    padding: 0px 8px;\n"
"}")
        self.closeBtn = QtWidgets.QPushButton(parent=Dialog)
        self.closeBtn.setGeometry(QtCore.QRect(60, 190, 113, 32))
        self.closeBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.closeBtn.setObjectName("closeBtn")
        self.cancelBtn = QtWidgets.QPushButton(parent=Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(240, 190, 131, 32))
        self.cancelBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cancelBtn.setObjectName("cancelBtn")
        self.teacehrLable = QtWidgets.QLabel(parent=Dialog)
        self.teacehrLable.setGeometry(QtCore.QRect(60, 60, 131, 21))
        self.teacehrLable.setObjectName("teacehrLable")
        self.dateLable = QtWidgets.QLabel(parent=Dialog)
        self.dateLable.setGeometry(QtCore.QRect(60, 130, 111, 21))
        self.dateLable.setObjectName("dateLable")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(230, 130, 181, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 60, 181, 21))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Запись"))
        self.closeBtn.setText(_translate("Dialog", "Закрыть"))
        self.cancelBtn.setText(_translate("Dialog", "Отменить запись"))
        self.teacehrLable.setText(_translate("Dialog", "Преподаватель:"))
        self.dateLable.setText(_translate("Dialog", "Дата и время"))
        self.label.setText(_translate("Dialog", "Вы не записаны"))
