# Form implementation generated from reading ui file 'teacher_show_recordsUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(554, 502)
        Dialog.setStyleSheet("QDialog {\n"
"    background: #F5FaFE;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border-radius: 10px;\n"
"    background: #1E95FE;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid black;\n"
"    border-radius: 10px;\n"
"    padding: 0px 8px;\n"
"}")
        self.closeBtn = QtWidgets.QPushButton(parent=Dialog)
        self.closeBtn.setGeometry(QtCore.QRect(220, 440, 113, 32))
        self.closeBtn.setObjectName("closeBtn")
        self.teacherShowRecorTableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.teacherShowRecorTableWidget.setGeometry(QtCore.QRect(20, 20, 521, 401))
        self.teacherShowRecorTableWidget.setObjectName("teacherShowRecorTableWidget")
        self.teacherShowRecorTableWidget.setColumnCount(0)
        self.teacherShowRecorTableWidget.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Записи"))
        self.closeBtn.setText(_translate("Dialog", "Закрыть"))
